#  შემოატანინეთ მომხმარებელს 20 ინტი და
#  შემდგომში მოახდინეთ მათზე
#  მათემატიკური ოპერაციები

n=int(input("enter a number"))
b=(int(input("enter a number")))
c=(int(input("enter a number")))
a=(int(input("enter a number")))
rop=(int(input("enter a number")))
y=(int(input("enter a number")))
j=(int(input("enter a number")))
om=(int(input("enter a number")))
ok=(int(input("enter a number")))
jgohjgtoijgeij=(int(input("enter a number")))
fj=(int(input("enter a number")))
jhm=(int(input("enter a number")))
ygh=(int(input("enter a number")))
ufih=(int(input("enter a number")))
tu=(int(input("enter a number")))
di=(int(input("enter a number")))
fhu=(int(input("enter a number")))
ggfrhr4=(int(input("enter a number")))
v=(int(input("enter a number")))
gugut=(int(input("enter a number")))
print(n*b)
print(c-a)
print(rop//y)
print(j+om)
print(ok*jgohjgtoijgeij)
print(fj%jhm)
print(ggfrhr4/v)
print(tu%di)
print(v*gugut)
print(jhm%ygh)
